"""The v4.0 historical inventory: every deferral, non-goal and open item since v2.0.0, classified.

The pre-v4 audit (v3.10) inventoried ROADMAP's boundaries and its optional
list; v3.13 added the "Known limitations" and "DEFERRED" lists of ADR-0042 to
ADR-0044 (TST-015). Neither read the v2-era ADRs' "Explicit non-goals", "Not in
scope" and "Consequences of deferring" sections, nor the CHANGELOG's "Known
gaps", "Known Limitations", "Not in scope", "Deferred, unchanged", "Recorded"
and "Still open" sections, nor ``nowandfuture.md``'s open questions. The v4.0
archaeology did (ledger TST-017), and two of those items hid live defects:
ADR-0029's "no live-object parameter persistence" (PER-008) and the
non-resumable replay ADR-0029 and ADR-0030 deferred, which nothing had tracked
since (FUT-001).

This script is the classification. :data:`CLASSIFICATION` holds, for each
source section, one row per item -- matched by the item's opening words -- with
its status, the ledger entries or code that are its evidence, and a note. The
ledger entry for each section (``HIS-xxx``) is written from it, and so is
``docs/audit/V4_HISTORICAL_INVENTORY.md``.

    python docs/audit/scripts/historical_inventory_v4.py --write   # ledger block + document
    python docs/audit/scripts/historical_inventory_v4.py --check   # fails if either is stale

``tests/regression/test_every_adr_deferral_is_classified.py`` reads the ADRs and
the CHANGELOG through :func:`stated_items` and holds every item to exactly one
row, and the generated files to this script.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
LEDGER = ROOT / "docs" / "audit" / "PRE_V4_COMPLETION_LEDGER.yaml"
DOCUMENT = ROOT / "docs" / "audit" / "V4_HISTORICAL_INVENTORY.md"
MARKER = (
    "  # --- v4.0 historical inventory: generated by docs/audit/scripts/historical_inventory_v4.py"
)

#: What an item's status may be, and what it means.
STATUSES: dict[str, str] = {
    "DELIVERED": "built in a later release; the evidence names it",
    "FIXED-v4": "a defect the item concealed, fixed in v4.0 with a regression test",
    "BOUNDARY": "kept out on purpose, with the reason the ledger entry gives",
    "LIMITATION": "kept as a stated limitation, with its reason",
    "EXTERNAL": "real, and the host application's or a vendor's to supply",
    "REMOVED": "the thing the item was about left the library",
    "EXPIRED": "a fence around one release's scope, which ended with that release",
    "SUPERSEDED": "replaced by a later decision, which the evidence names",
    "FUTURE": "accepted future work, on the ROADMAP with acceptance criteria",
}


@dataclass(frozen=True)
class Section:
    """One place history stated deferred work, and the ledger entry that classifies it."""

    ledger_id: str
    path: str
    heading: str
    origin: str
    #: "bullets" (one item per bullet), "semicolons" (prose list split on "; ")
    #: or "whole" (the section is one item).
    shape: str


SECTIONS: tuple[Section, ...] = (
    Section(
        "HIS-001",
        "docs/ADR/0010-unified-backtesting-and-replay.md",
        "Not in scope",
        "v2.2.0, ADR-0010",
        "bullets",
    ),
    Section(
        "HIS-002",
        "docs/ADR/0011-canonical-market-data-model.md",
        "Not in scope",
        "v2.3.0, ADR-0011",
        "bullets",
    ),
    Section(
        "HIS-003",
        "docs/ADR/0012-broker-boundary-and-environment-parity.md",
        "Not in scope",
        "v2.3.0, ADR-0012",
        "bullets",
    ),
    Section(
        "HIS-004",
        "docs/ADR/0015-allocation-authority-and-attribution-truth.md",
        "Not in scope",
        "v2.6.0, ADR-0015",
        "whole",
    ),
    Section(
        "HIS-005",
        "docs/ADR/0016-instrument-identity-and-resolution-authority.md",
        "Explicit non-goals",
        "v2.7.0, ADR-0016",
        "bullets",
    ),
    Section(
        "HIS-006",
        "docs/ADR/0017-dataset-identity-and-evidence-derivation.md",
        "Explicit non-goals",
        "v2.7.0, ADR-0017",
        "bullets",
    ),
    Section(
        "HIS-007",
        "docs/ADR/0018-governance-actors-lifecycle-enterprise-boundary.md",
        "Explicit non-goals",
        "v2.7.0, ADR-0018",
        "bullets",
    ),
    Section(
        "HIS-008",
        "docs/ADR/0018-governance-actors-lifecycle-enterprise-boundary.md",
        "Consequences of deferring",
        "v2.7.0, ADR-0018",
        "whole",
    ),
    Section(
        "HIS-009",
        "docs/ADR/0019-currency-roles-and-settlement-semantics.md",
        "Explicit non-goals",
        "v2.8.0, ADR-0019",
        "bullets",
    ),
    Section(
        "HIS-010",
        "docs/ADR/0020-mixed-currency-aggregation-boundary.md",
        "Explicit non-goals",
        "v2.8.0, ADR-0020",
        "bullets",
    ),
    Section(
        "HIS-011",
        "docs/ADR/0021-run-outcomes-and-contribution-retirement.md",
        "Explicit non-goals",
        "v2.8.0, ADR-0021",
        "bullets",
    ),
    Section(
        "HIS-012",
        "docs/ADR/0022-deterministic-identifier-continuation.md",
        "Explicit non-goals",
        "v2.9.0, ADR-0022",
        "bullets",
    ),
    Section(
        "HIS-013",
        "docs/ADR/0023-run-state-snapshot-envelope.md",
        "Explicit non-goals",
        "v2.9.0, ADR-0023",
        "bullets",
    ),
    Section(
        "HIS-014",
        "docs/ADR/0024-external-order-recovery-without-a-venue.md",
        "Explicit non-goals",
        "v2.9.0, ADR-0024",
        "bullets",
    ),
    Section(
        "HIS-015",
        "docs/ADR/0025-strategy-state-ownership-and-capture-contract.md",
        "Explicit non-goals",
        "v2.10.0, ADR-0025",
        "bullets",
    ),
    Section(
        "HIS-016",
        "docs/ADR/0026-strategy-context-population-and-visibility-boundary.md",
        "Explicit non-goals",
        "v2.10.0, ADR-0026",
        "bullets",
    ),
    Section(
        "HIS-017",
        "docs/ADR/0027-instrument-classification-and-sector-provenance.md",
        "Explicit non-goals",
        "v2.11.0, ADR-0027",
        "bullets",
    ),
    Section(
        "HIS-018",
        "docs/ADR/0028-currency-authority-and-the-settlement-boundary.md",
        "Explicit non-goals",
        "v2.12.0, ADR-0028",
        "bullets",
    ),
    Section(
        "HIS-019",
        "docs/ADR/0029-run-state-store-and-the-durability-boundary.md",
        "Explicit non-goals",
        "v2.13.0, ADR-0029",
        "bullets",
    ),
    Section(
        "HIS-020",
        "docs/ADR/0030-run-runtime-and-the-final-driver-boundary.md",
        "Explicit non-goals",
        "v2.14.0, ADR-0030",
        "bullets",
    ),
    Section(
        "HIS-021",
        "docs/ADR/0031-real-transport-streaming-artifacts-and-the-completed-boundaries.md",
        "Explicit non-goals",
        "v2.15.0, ADR-0031",
        "bullets",
    ),
    Section(
        "HIS-022",
        "docs/ADR/0032-the-refactor-audit-and-the-v3-condition.md",
        "Explicit non-goals",
        "v2.16.0, ADR-0032",
        "bullets",
    ),
    Section(
        "HIS-023",
        "docs/ADR/0033-the-integrated-runtime-governance-and-fx.md",
        "Explicit non-goals",
        "v2.16.0, ADR-0033",
        "bullets",
    ),
    Section(
        "HIS-024",
        "docs/ADR/0034-the-final-engineering-release.md",
        "Explicit non-goals",
        "v2.16.0, ADR-0034",
        "bullets",
    ),
    Section(
        "HIS-025",
        "docs/ADR/0035-settlement-currency-the-fx-feed-and-the-strategy-registry.md",
        "Explicit non-goals",
        "v2.17.0, ADR-0035",
        "bullets",
    ),
    Section(
        "HIS-026",
        "CHANGELOG.md#2.0.0",
        "Known gaps (unchanged in 2.0.0)",
        "v2.0.0, CHANGELOG",
        "bullets",
    ),
    Section(
        "HIS-027",
        "CHANGELOG.md#2.1.0",
        "Known Limitations",
        "v2.1.0, CHANGELOG",
        "bullets",
    ),
    Section(
        "HIS-028",
        "CHANGELOG.md#2.6.0",
        "Not in scope",
        "v2.6.0, CHANGELOG",
        "whole",
    ),
    Section(
        "HIS-029",
        "CHANGELOG.md#2.8.0",
        "Deferred, unchanged",
        "v2.8.0, CHANGELOG",
        "semicolons",
    ),
    Section(
        "HIS-030",
        "CHANGELOG.md#2.9.0",
        "Deferred, unchanged",
        "v2.9.0, CHANGELOG",
        "semicolons",
    ),
    Section(
        "HIS-031",
        "CHANGELOG.md#2.10.0",
        "Deferred, unchanged",
        "v2.10.0, CHANGELOG",
        "semicolons",
    ),
    Section(
        "HIS-032",
        "CHANGELOG.md#2.11.0",
        "Deferred, unchanged",
        "v2.11.0, CHANGELOG",
        "semicolons",
    ),
    Section(
        "HIS-033",
        "CHANGELOG.md#2.16.0",
        "Recorded — optional post-v3.0 evolution, not implemented here",
        "v2.16.0, CHANGELOG",
        "semicolons",
    ),
    Section(
        "HIS-034",
        "CHANGELOG.md#3.10.0",
        "Still open — the rest of the pre-v4 plan",
        "v3.10.0, CHANGELOG",
        "whole",
    ),
    Section(
        "HIS-035",
        "CHANGELOG.md#3.11.0",
        "Still open — the rest of the pre-v4 plan",
        "v3.11.0, CHANGELOG",
        "whole",
    ),
    Section(
        "HIS-036",
        "CHANGELOG.md#3.12.0",
        "Still open",
        "v3.12.0, CHANGELOG",
        "whole",
    ),
    Section(
        "HIS-037",
        "CHANGELOG.md#3.13.0",
        "Still open",
        "v3.13.0, CHANGELOG",
        "bullets",
    ),
    Section(
        "HIS-038",
        "nowandfuture.md",
        "20. Open questions",
        "v3.0.0 to v3.13.0, nowandfuture.md",
        "bullets",
    ),
    Section(
        "HIS-039",
        "docs/architecture/strategy/STRATEGY_RUNTIME_DESIGN.md",
        "11. Open Questions for Future Phases",
        "v1.x design, STRATEGY_RUNTIME_DESIGN.md",
        "bullets",
    ),
)

#: (prefix of the item's normalized text, status, evidence, note), per section.
Row = tuple[str, str, str, str]

CLASSIFICATION: dict[str, tuple[Row, ...]] = {
    "HIS-001": (
        (
            "Market-data model convergence",
            "DELIVERED",
            "ADR-0011; SCF-002 (v3.10)",
            (
                "One canonical market model (alphalab.market) since v2.3; the "
                "feed/live/marketdata engine scaffolds removed in v3.10."
            ),
        ),
        (
            "broker / brokers consolidation",
            "DELIVERED",
            "ADR-0012; ADR-0044; tests/regression/test_shared_names_stay_distinct.py",
            (
                "Two packages kept on purpose (one venue / a connector over many), one vocabulary"
                " since v2.3; the live path routes through the broker boundary since v2.16."
            ),
        ),
        (
            "Resolution of kernel and core/events",
            "REMOVED",
            "CHANGELOG 2.17.0 section 5",
            "kernel, core.events and CommonEvent removed in v2.17.0.",
        ),
    ),
    "HIS-002": (
        (
            "Vendor connectivity.",
            "REMOVED",
            "BND-001 (v3.10); OFE-008",
            (
                "Vendor clients removed in v3.10; vendor adapters are the host application's "
                "(EXTERNAL)."
            ),
        ),
        (
            "alphalab.marketdata.symbols.AssetClass",
            "REMOVED",
            "OFE-012 (v3.10)",
            "The duplicate enum left with marketdata's provider layer.",
        ),
        (
            "alphalab.data's non-market records",
            "DELIVERED",
            "OFE-009 (v3.12); ADR-0042",
            (
                "Point-in-time observations, events and fundamentals reach the execution path "
                "since v3.12."
            ),
        ),
    ),
    "HIS-003": (
        (
            "Strategies still do not receive the marked portfolio",
            "DELIVERED",
            "ADR-0026 (v2.10)",
            "The pipeline overlays the marked portfolio onto every context.",
        ),
        (
            "The pipeline still mints a fresh order per market event",
            "DELIVERED",
            "EXE-003 (v3.11)",
            "Resting simulated orders with time in force since v3.11.",
        ),
        (
            "An async live session loop",
            "BOUNDARY",
            "BDY-011",
            (
                "No supervised process; LiveSession.advance is driven by the host. Reconnect is "
                "in the WebSocket client since v2.15."
            ),
        ),
    ),
    "HIS-004": (
        (
            "Carried forward, unchanged by this ADR",
            "DELIVERED",
            "ADR-0031; ADR-0035; ADR-0029; ADR-0033; ADR-0016; ADR-0030; BND-002; PER-001",
            (
                "Each delivered later: transport and streaming (v2.15), multi-currency valuation "
                "(v2.17), artifact storage (v2.15), dataset provenance (v2.7), a security master "
                "(v2.11), the run runtime (v2.14), lifecycle-to-execution (v2.16), OMS "
                "schema_version (v2.9); enterprise RBAC left the library (v3.11); integrations, "
                "kernel, core.events and CommonEvent removed (v2.17)."
            ),
        ),
    ),
    "HIS-005": (
        (
            "Sector classification data",
            "EXTERNAL",
            "BDY-013",
            "AlphaLab ships no reference data; the mechanism since v2.11.",
        ),
        (
            "A corporate-actions, listings or reference-data feed",
            "EXTERNAL",
            "BDY-013",
            "The arithmetic is the library's; the data is the host's.",
        ),
        (
            "Deleting or merging the five asset-class enums",
            "DELIVERED",
            "OFE-012 (v3.10); tests/regression/test_shared_names_stay_distinct.py",
            "Two provider duplicates removed; the remaining enums are distinct and pinned.",
        ),
        (
            "Reviving marketdata.SymbolMetadata",
            "REMOVED",
            "SCF-002 (v3.10)",
            "Removed with marketdata's engine layer.",
        ),
        (
            "Validating asset_id inside Intent",
            "BOUNDARY",
            "ADR-0016",
            (
                "One boundary: resolution at normalization; an unregistered asset is an unpriced "
                "outcome."
            ),
        ),
        (
            "Detecting an Intent that names an unresolved",
            "DELIVERED",
            "alphalab/runtime/execution_pipeline.py:UnpricedReason",
            "UnpricedReason.NOT_REGISTERED, reported per asset.",
        ),
        (
            "Any change to Fill / Trade validation",
            "EXPIRED",
            "ADR-0044",
            "A v2.7 scope fence; v3.9 changed fill validation deliberately.",
        ),
    ),
    "HIS-006": (
        (
            "Content-addressed or registry-issued dataset ids",
            "DELIVERED",
            "ADR-0036; KD-004 (v3.10)",
            (
                "A dataset version is derived from its content since v3.1; rows-ingested identity"
                " since v3.10."
            ),
        ),
        (
            "A dataset registry, or any uniqueness guarantee",
            "BOUNDARY",
            "ADR-0036",
            "A version identifies content; storing datasets is the host's.",
        ),
        (
            "Adding fields to ValidationEvidence",
            "EXPIRED",
            "ADR-0017",
            "A v2.7 scope fence.",
        ),
        (
            "Adding a dataset component to release_manifest()",
            "SUPERSEDED",
            "ADR-0041",
            "The reproducibility manifest (v3.6) names the dataset.",
        ),
        (
            "Any lifecycle schema version movement",
            "EXPIRED",
            "ADR-0018",
            "A v2.7 scope fence; the lifecycle schema moved in v2.16.",
        ),
        (
            "Wiring alphalab.data.DatasetMetadata to the execution path",
            "DELIVERED",
            "alphalab/api.py:backtest",
            "BacktestResult.dataset_id carries the dataset version since v3.1.",
        ),
        (
            "Giving ResearchState a dataset reference",
            "SUPERSEDED",
            "ADR-0037",
            "Research studies name their dataset version (v3.2).",
        ),
    ),
    "HIS-007": (
        (
            "Authentication, credentials, password or key handling",
            "BOUNDARY",
            "BDY-010; BRK-007; BND-002",
            "Permanent; enterprise left the library in v3.11.",
        ),
        (
            "A full IAM system",
            "BOUNDARY",
            "BDY-010",
            "Permanent.",
        ),
        (
            "Auto-emitted audit events from RBAC",
            "REMOVED",
            "BND-002 (v3.11)",
            "RBAC left the library; PermissionAuthority is the host's.",
        ),
        (
            "Coupling LifecycleState to EnterpriseState",
            "REMOVED",
            "BND-002 (v3.11)",
            "EnterpriseState no longer exists.",
        ),
        (
            "Per-environment promotion policy",
            "BOUNDARY",
            "BDY-004",
            "One stage per strategy version.",
        ),
    ),
    "HIS-008": (
        (
            "Accepted for now.",
            "DELIVERED",
            "ADR-0018 (v2.16 amendment); alphalab/lifecycle",
            "Governance actors are recorded on lifecycle transitions since v2.16.",
        ),
    ),
    "HIS-009": (
        (
            "Any FX rate source, conversion",
            "DELIVERED",
            "ADR-0033; ADR-0035",
            (
                "Conversion with stated rates since v2.16; the rate feed boundary v2.17; no rate "
                "data (EXTERNAL)."
            ),
        ),
        (
            "Any change to asset_id derivation",
            "BOUNDARY",
            "tests/regression/test_instrument_identity_reaches_a_fill.py",
            "Identity derivation is frozen.",
        ),
        (
            "Extending the currency check to NAVCalculator",
            "SUPERSEDED",
            "ADR-0028 decision 7",
            "Settled as the ADR's own amendment states.",
        ),
        (
            "Normalizing or case-folding currency codes",
            "BOUNDARY",
            "alphalab/common/currency.py",
            "Codes are compared as written.",
        ),
        (
            "Deriving a canonical record's venue",
            "BOUNDARY",
            "tests/regression/test_venue_concepts_stay_distinct.py",
            "Listing exchange and execution venue are distinct concepts.",
        ),
        (
            "Restricting foreign-currency instruments",
            "BOUNDARY",
            "ADR-0035",
            "Held and booked under settlement-currency rules.",
        ),
    ),
    "HIS-010": (
        (
            "An FX rate source, provider, or conversion",
            "DELIVERED",
            "ADR-0033; ADR-0035",
            "As HIS-009.",
        ),
        (
            "Rate caching, triangulation",
            "BOUNDARY",
            "BDY-009",
            "No implicit FX.",
        ),
        (
            "Extending the refusal to portfolio_value",
            "SUPERSEDED",
            "ADR-0028",
            "Done for two, declined for two, with reasons.",
        ),
        (
            "Preventing foreign-currency instruments",
            "BOUNDARY",
            "ADR-0035",
            "As HIS-009.",
        ),
        (
            "Per-currency sub-valuations returned as a breakdown",
            "BOUNDARY",
            "ADR-0035; API-004",
            "No per-currency equity; BacktestResult.valuation_in values in a stated currency.",
        ),
    ),
    "HIS-011": (
        (
            "Retiring a reservation or contribution for an order that is still working",
            "BOUNDARY",
            "ADR-0021; tests/regression/test_contributions_are_retired.py",
            "Retired at a terminal outcome only.",
        ),
        (
            "A terminal bridge for externally routed orders",
            "DELIVERED",
            "ADR-0024",
            "Delivered in v2.9.",
        ),
        (
            "Persisting AllocationState",
            "DELIVERED",
            "ADR-0023",
            "alphalab.allocation.snapshot since v2.9.",
        ),
        (
            "Changing how attribution is computed",
            "EXPIRED",
            "ADR-0021",
            "A v2.8 scope fence.",
        ),
        (
            "Changing the budget pre-check",
            "EXPIRED",
            "ALC-007 (v3.11); OFE-003 (v3.12)",
            "A v2.8 scope fence; the budget changed deliberately later.",
        ),
    ),
    "HIS-012": (
        (
            "A PRNG registry",
            "BOUNDARY",
            "ADR-0022",
            "One seeded stream per run.",
        ),
        (
            "A generator-version field",
            "BOUNDARY",
            "ADR-0022",
            "Versioned by the snapshot schema.",
        ),
        (
            "Serializing generator internal state",
            "BOUNDARY",
            "ADR-0022; tests/regression/test_id_stream_continuation.py",
            "A position, not generator state, is persisted.",
        ),
        (
            "Removing or replacing the ContextVar",
            "BOUNDARY",
            "alphalab/common/ids.py",
            "id_scope still installs the stream.",
        ),
        (
            "Threading an id source through engine signatures",
            "BOUNDARY",
            "ADR-0022",
            "Unchanged.",
        ),
        (
            "Any change to asset_id derivation",
            "BOUNDARY",
            "tests/regression/test_instrument_identity_reaches_a_fill.py",
            "Frozen.",
        ),
        (
            "Per-category or per-engine identifier streams",
            "BOUNDARY",
            "ADR-0022",
            "Unchanged; replay's second stream is FUT-001's concern.",
        ),
    ),
    "HIS-013": (
        (
            "A migration framework or version-translation layer",
            "DELIVERED",
            "PER-001; BDY-007 (v3.10)",
            "Schema histories upgrade every older payload.",
        ),
        (
            "Schema constants for Market, Risk, Execution",
            "SUPERSEDED",
            "ADR-0023",
            "Nested inside the pipeline payload's version.",
        ),
        (
            "Persisting BrokerState or ExternalOrderMap",
            "DELIVERED",
            "ADR-0024; alphalab/broker/snapshot.py",
            "Broker snapshot since v2.16.",
        ),
        (
            "A StrategyStateProtocol",
            "DELIVERED",
            "ADR-0025 (v2.10)",
            "StrategyStateProtocol.",
        ),
        (
            "StrategyContext completion",
            "DELIVERED",
            "ADR-0026 (v2.10)",
            "Populated contexts.",
        ),
        (
            "Unifying SessionState and BacktestState",
            "DELIVERED",
            "ADR-0030 (v2.14)",
            "One RunState.",
        ),
        (
            "Moving PORTFOLIO_SNAPSHOT_SCHEMA",
            "EXPIRED",
            "docs/STATE_MODEL.md",
            "A v2.9 scope fence; both moved later with upgrades.",
        ),
        (
            "Capturing LifecycleState into this envelope",
            "BOUNDARY",
            "ADR-0023",
            "A deployment's lifetime, not a run's.",
        ),
    ),
    "HIS-014": (
        (
            "Broker transport, credentials",
            "BOUNDARY",
            "BDY-010; BRK-007",
            "Transport is protocol code; credentials and vendor adapters are the host's.",
        ),
        (
            "Persisting BrokerState, ExternalOrderMap",
            "DELIVERED",
            "alphalab/broker/snapshot.py",
            "Since v2.16.",
        ),
        (
            "Driving reconcile automatically on resume",
            "BOUNDARY",
            "BDY-005",
            "Detection without remediation.",
        ),
        (
            "Unifying OMSState and BrokerState",
            "BOUNDARY",
            "tests/regression/test_shared_names_stay_distinct.py",
            "Book and venue mirror stay distinct.",
        ),
        (
            "Importing alphalab.broker from the pipeline",
            "SUPERSEDED",
            "ADR-0033",
            "The integrated runtime imports the broker boundary since v2.16.",
        ),
        (
            "Inventing a fill, a cancellation",
            "BOUNDARY",
            "ADR-0044",
            "Every venue report has one meaning; nothing is invented.",
        ),
    ),
    "HIS-015": (
        (
            "Arbitrary object pickling",
            "BOUNDARY",
            "alphalab/persistence/decode.py",
            "Permanent.",
        ),
        (
            "Reflective object reconstruction",
            "BOUNDARY",
            "alphalab/persistence/decode.py",
            "Permanent.",
        ),
        (
            "A new encoder branch",
            "EXPIRED",
            "ADR-0025",
            "A v2.10 scope fence.",
        ),
        (
            "StrategyContext design or population",
            "DELIVERED",
            "ADR-0026",
            "v2.10.",
        ),
        (
            "Reviving on_fill, on_order, on_timer",
            "DELIVERED",
            "OFE-014; EXE-005 (v3.11)",
            "Pipeline-driven hooks since v3.11.",
        ),
        (
            "Runtime unification",
            "DELIVERED",
            "ADR-0030",
            "One RunState since v2.14.",
        ),
        (
            "Unifying SnapshotDecodeError with StateDecodeError",
            "BOUNDARY",
            (
                "tests/regression/test_durable_run_continuation.py::test_a_nested_oms_failure_keeps_its_own_error_type"
            ),
            "Each decoder keeps its own error type.",
        ),
        (
            "Redefining StrategyRecord.config semantics",
            "LIMITATION",
            "LIM-004",
            (
                "Kept: a configuration holding a Decimal or a tuple reads back as a string or a "
                "list; nothing on the execution path reads it, and a run's identity is "
                "unaffected."
            ),
        ),
        (
            "A capture cadence, a scheduler",
            "BOUNDARY",
            "ADR-0025",
            (
                "When to snapshot is the caller's; checkpoints since v3.12 are taken when the "
                "caller asks."
            ),
        ),
        (
            "Cross-strategy state, shared state",
            "BOUNDARY",
            "ADR-0025",
            "Unchanged.",
        ),
    ),
    "HIS-016": (
        (
            "Historical data access.",
            "DELIVERED",
            "ADR-0026; tests/regression/test_strategy_context_visibility.py",
            "StrategyContext.history bounded at the event.",
        ),
        (
            "Universe.",
            "DELIVERED",
            "alphalab/strategy/context.py",
            "StrategyContext.universe.",
        ),
        (
            "Allocation visibility.",
            "BOUNDARY",
            "BDY-002",
            "Unchanged.",
        ),
        (
            "Mutable runtime services",
            "BOUNDARY",
            "ADR-0026",
            "Permanent.",
        ),
        (
            "Reviving on_fill, on_order, on_timer",
            "DELIVERED",
            "OFE-014; EXE-005 (v3.11)",
            "As HIS-015.",
        ),
        (
            "Runtime unification.",
            "DELIVERED",
            "ADR-0030",
            "As HIS-015.",
        ),
        (
            "config semantics, in either sense",
            "LIMITATION",
            "LIM-004",
            "As HIS-015.",
        ),
        (
            "Reopening ADR-0025.",
            "EXPIRED",
            "ADR-0026",
            "A v2.10 scope fence.",
        ),
        (
            "Context pooling or arena allocation.",
            "BOUNDARY",
            "ADR-0026",
            "Not needed: the routing index (PRF-010) bounds per-event work.",
        ),
        (
            "Changing ContextFactory's signature.",
            "BOUNDARY",
            "alphalab/runtime/execution_pipeline.py:ContextFactory",
            "Unchanged.",
        ),
    ),
    "HIS-017": (
        (
            "Any sector taxonomy, classification dataset",
            "EXTERNAL",
            "BDY-013",
            "No reference data.",
        ),
        (
            "Any classification dimension other than sector",
            "DELIVERED",
            "OFE-001 (v3.12)",
            "Classification dimensions beyond sector.",
        ),
        (
            "A canonical or case-folded sector vocabulary",
            "BOUNDARY",
            "ADR-0027",
            "Labels are the caller's.",
        ),
        (
            "Distinguishing *why* a sector is unknown",
            "BOUNDARY",
            "ADR-0027",
            (
                "An unclassified instrument is reported as unclassified; the reason is the host's"
                " data."
            ),
        ),
        (
            "Persisting the InstrumentRegistry, or checking on restore",
            "DELIVERED",
            "alphalab/instrument/snapshot.py",
            (
                "Persisted since v2.15; restore still does not compare classification (ADR-0027 "
                "decision 5), and v4.0's PER-008 leaves the registry out for that reason."
            ),
        ),
        (
            "Sector-based risk limits",
            "DELIVERED",
            "OFE-001 (v3.12)",
            "Classification-bucket limits.",
        ),
        (
            "InstrumentRecord.currency reaching Position.currency",
            "DELIVERED",
            "ADR-0028",
            "v2.12.",
        ),
        (
            "Any change to alphalab.analytics.",
            "EXPIRED",
            "ADR-0027",
            "A v2.11 scope fence.",
        ),
        (
            "Any change to instrument identity derivation",
            "BOUNDARY",
            "tests/regression/test_instrument_identity_reaches_a_fill.py",
            "Frozen.",
        ),
    ),
    "HIS-018": (
        (
            "Any FX rate source, rate type",
            "DELIVERED",
            "ADR-0033; ADR-0035; BDY-009",
            "Stated-rate conversion; no implicit FX.",
        ),
        (
            "Aggregating two currencies into one figure",
            "BOUNDARY",
            "ADR-0020",
            "MixedCurrencyValuationError stands; valuation_in states its rates.",
        ),
        (
            "A per-currency breakdown on PortfolioValuationSnapshot",
            "BOUNDARY",
            "ADR-0035",
            "Settlement records are per-currency; equity is not.",
        ),
        (
            "Per-currency minor units.",
            "DELIVERED",
            "ACC-001 (v3.10)",
            "alphalab.common.currency_units.",
        ),
        (
            "Automatic cash conversion on a foreign buy",
            "BOUNDARY",
            "ADR-0035",
            "An FX trade is a stated act.",
        ),
        (
            "Currency on TradeRecord, OrderRequest or oms.Order",
            "DELIVERED",
            "alphalab/analytics/attribution.py:TradeRecord",
            "TradeRecord's attribution facts carry the settlement currency (v3.3).",
        ),
        (
            "NormalizationPolicy.currency reaching the execution path",
            "BOUNDARY",
            "V09 mutation pin",
            "A normalization currency is the record's, not the pipeline's.",
        ),
        (
            "Collapsing Account.base_currency and ExecutionPipelineConfig.currency",
            "BOUNDARY",
            "ADR-0019",
            "Distinct roles.",
        ),
        (
            "Making ExecutionPipelineConfig.instruments mandatory",
            "BOUNDARY",
            "ADR-0028",
            "Optional; UnpricedReason says which reading applies.",
        ),
        (
            "An earlier settlement check inside route_order",
            "BOUNDARY",
            "ADR-0028",
            "Unchanged.",
        ),
        (
            "Narrowing PortfolioEngine.",
            "EXPIRED",
            "ADR-0028",
            "A v2.12 scope fence.",
        ),
        (
            "A durable settlement-refusal state field.",
            "DELIVERED",
            "alphalab/runtime/execution_pipeline.py:SettlementRefusal",
            "Settlement refusals are recorded on the run's state.",
        ),
        (
            "Any change to instrument identity, the namespace",
            "BOUNDARY",
            "tests/regression/test_instrument_identity_reaches_a_fill.py",
            "Frozen.",
        ),
        (
            "Sector- or currency-based risk limits.",
            "DELIVERED",
            "OFE-001 (v3.12)",
            "Classification-bucket limits read any declared dimension.",
        ),
    ),
    "HIS-019": (
        (
            "No FX, and no multi-currency valuation.",
            "DELIVERED",
            "ADR-0033; ADR-0035",
            "v2.16-v2.17.",
        ),
        (
            "No ArtifactStore",
            "DELIVERED",
            "ADR-0031; alphalab/model_registry",
            "Artifact storage since v2.15; the evidence store since v3.12 (OFE-016).",
        ),
        (
            "No cloud or vendor-specific storage",
            "BOUNDARY",
            "BDY-023",
            "Permanent.",
        ),
        (
            "No streaming.",
            "DELIVERED",
            "ADR-0031",
            "v2.15.",
        ),
        (
            "No live venue transport.",
            "DELIVERED",
            "ADR-0031; BRK-007",
            (
                "Protocol transports since v2.15; the credential-bearing transport moved to the "
                "test tree in v3.11."
            ),
        ),
        (
            "No broad runtime rewrite.",
            "EXPIRED",
            "ADR-0029",
            "A v2.13 scope fence.",
        ),
        (
            "No RunManager, run facade",
            "BOUNDARY",
            "ADR-0030",
            "The drivers hold no state.",
        ),
        (
            "No compatibility aliases and no re-exports.",
            "BOUNDARY",
            "ADR-0048 rejected alternatives",
            "No aliases at the freeze either.",
        ),
        (
            "No migration framework or version-translation layer.",
            "DELIVERED",
            "PER-001 (v3.10)",
            "As HIS-013.",
        ),
        (
            "No schema move for convenience",
            "BOUNDARY",
            "docs/STATE_MODEL.md",
            "Every move since is for a recorded field.",
        ),
        (
            "No change to ArtifactRef",
            "EXPIRED",
            "ADR-0029",
            "A v2.13 scope fence.",
        ),
        (
            "No removal of any deprecated package in this release.",
            "EXPIRED",
            "CHANGELOG 2.17.0 section 5",
            "Removed in v2.17.",
        ),
        (
            "No replay resumability.",
            "FUTURE",
            "FUT-001",
            (
                "Still true at v4.0: a replay cannot be snapshotted and resumed. A backtest of "
                "the same dataset can, and produces the same orders, fills and P&L."
            ),
        ),
        (
            "No live-object parameter persistence.",
            "FIXED-v4",
            "PER-008; tests/regression/test_restore_requires_the_captured_configuration.py",
            (
                "The defect this concealed: a restore accepted a simulator with another "
                "commission rate. v4.0 records each live object's configuration and refuses a "
                "mismatch."
            ),
        ),
        (
            "No trimming of the payload.",
            "DELIVERED",
            "PRF-004 (v3.12); PRF-011 (v3.13)",
            "Retention policies and incremental checkpoints.",
        ),
    ),
    "HIS-020": (
        (
            "No streaming implementation.",
            "DELIVERED",
            "ADR-0031",
            "v2.15.",
        ),
        (
            "No live venue transport.",
            "DELIVERED",
            "ADR-0031",
            "As HIS-019.",
        ),
        (
            "No FX and no multi-currency valuation.",
            "DELIVERED",
            "ADR-0033; ADR-0035",
            "As HIS-019.",
        ),
        (
            "No artifact storage",
            "DELIVERED",
            "ADR-0031; OFE-016",
            "As HIS-019.",
        ),
        (
            "No governance, RBAC or approval workflow.",
            "DELIVERED",
            "ADR-0033; BND-002",
            (
                "Governance on the lifecycle since v2.16; RBAC is the host's PermissionAuthority "
                "since v3.11."
            ),
        ),
        (
            "No replay resumability (decision 10).",
            "FUTURE",
            "FUT-001",
            "As HIS-019.",
        ),
        (
            "No removal of any deprecated package.",
            "EXPIRED",
            "CHANGELOG 2.17.0 section 5",
            "As HIS-019.",
        ),
        (
            "No RunDriver protocol.",
            "BOUNDARY",
            "ADR-0030; ADR-0033",
            "A driver is a shape, not an interface.",
        ),
        (
            "No change to RunStateStore",
            "EXPIRED",
            "ADR-0030",
            "A v2.14 scope fence.",
        ),
        (
            "No migration framework, compatibility alias",
            "DELIVERED",
            "PER-001",
            "Migration delivered; no alias or silent fallback stands.",
        ),
    ),
    "HIS-021": (
        (
            "A vendor adapter.",
            "EXTERNAL",
            "OFE-008",
            "The host application's.",
        ),
        (
            "Verification against a commercial endpoint.",
            "EXTERNAL",
            "ROADMAP External dependencies",
            "No egress, no credentials here.",
        ),
        (
            "permessage-deflate, or the server side of RFC 6455.",
            "BOUNDARY",
            "BND-006",
            "Kept as stated.",
        ),
        (
            "Allocation visibility in the strategy context",
            "BOUNDARY",
            "BDY-002",
            "As HIS-016.",
        ),
        (
            "Overlaying StrategyContext.clock",
            "BOUNDARY",
            "ADR-0031 decision 10",
            "The clock is the caller's.",
        ),
        (
            "Methods on MarketViewProtocol",
            "DELIVERED",
            "alphalab/strategy/context.py:MarketViewProtocol",
            "The view protocols are typed with members since v2.16-v3.11.",
        ),
        (
            "Any classification dimension other than sector",
            "DELIVERED",
            "OFE-001",
            "As HIS-017.",
        ),
        (
            "A second FX or currency behaviour.",
            "EXPIRED",
            "ADR-0031",
            "A v2.15 scope fence.",
        ),
        (
            "Removing the deprecated alphalab.production",
            "REMOVED",
            "CHANGELOG 2.17.0 section 5",
            "Removed in v2.17.",
        ),
        (
            "An integrated live runtime process.",
            "BOUNDARY",
            "BDY-011",
            "LiveSession is a driver; supervising a process is the host's.",
        ),
    ),
    "HIS-022": (
        (
            "Renaming a public symbol to resolve a name collision.",
            "DELIVERED",
            "API-001 (v3.13)",
            "52 shared names reduced to 31, each kept with a recorded reason.",
        ),
        (
            "Converting the ten remaining packages to the canonical containers.",
            "DELIVERED",
            "CHANGELOG 2.17.0 section 4",
            "Every ADR-0032 category C item delivered in v2.17.",
        ),
        (
            "Removing anything already deprecated.",
            "REMOVED",
            "CHANGELOG 2.17.0 section 5",
            "Removed in v2.17.",
        ),
        (
            "Routing depth events to a strategy hook.",
            "BOUNDARY",
            "BDY-003",
            "No depth hook.",
        ),
        (
            "Weakening benchmark_workbench.py",
            "REMOVED",
            "BND-003 (v3.11)",
            "The workbench left the library.",
        ),
    ),
    "HIS-023": (
        (
            "No second run state",
            "BOUNDARY",
            "ADR-0033",
            "Unchanged.",
        ),
        (
            "No RunDriver protocol.",
            "BOUNDARY",
            "ADR-0030",
            "As HIS-020.",
        ),
        (
            "No feed abstraction for fills.",
            "BOUNDARY",
            "ADR-0033",
            "advance takes the executions that arrived.",
        ),
        (
            "No cancel-on-disconnect",
            "BOUNDARY",
            "ADR-0033",
            "A consequence at a venue belongs to a person.",
        ),
        (
            "No authentication, credentials, IAM",
            "BOUNDARY",
            "BDY-010",
            "Permanent.",
        ),
        (
            "No EnterpriseState field on LifecycleState.",
            "REMOVED",
            "BND-002",
            "EnterpriseState no longer exists.",
        ),
        (
            "No FX triangulation, caching",
            "BOUNDARY",
            "BDY-009",
            "Permanent.",
        ),
        (
            "No settlement-level multi-currency trading.",
            "DELIVERED",
            "ADR-0035 (v2.17)",
            "also_settles.",
        ),
        (
            "No rate feed.",
            "DELIVERED",
            "ADR-0035",
            "The feed boundary since v2.17; no rate data (EXTERNAL).",
        ),
        (
            "Nothing from ADR-0032's category C.",
            "DELIVERED",
            "CHANGELOG 2.17.0 section 4",
            "Delivered in v2.17.",
        ),
    ),
    "HIS-024": (
        (
            "Starting v3.0's identity or documentation freeze.",
            "DELIVERED",
            "ADR-0034; CHANGELOG 3.0.0",
            "v3.0.",
        ),
        (
            "Optimizing PersistentMap lookup.",
            "DELIVERED",
            "PRF-002 (v3.10); PRF-008 (v3.11)",
            "Compaction and rebasing.",
        ),
        (
            "Reopening ADR-0032's category B.",
            "EXPIRED",
            "ADR-0034",
            "A v2.16 scope fence.",
        ),
        (
            "Adding filterwarnings anywhere.",
            "BOUNDARY",
            "tests/regression/test_the_suite_reports_nothing_deferred.py",
            "Zero warnings, enforced.",
        ),
        (
            "Keeping a deprecated module alive",
            "BOUNDARY",
            "ADR-0034",
            "Unchanged.",
        ),
    ),
    "HIS-025": (
        (
            "No implicit FX anywhere.",
            "BOUNDARY",
            "BDY-009",
            "Permanent.",
        ),
        (
            "No per-currency equity.",
            "BOUNDARY",
            "ADR-0020",
            "Unchanged.",
        ),
        (
            "No rate table on run configuration",
            "BOUNDARY",
            (
                "tests/regression/test_fx_valuation.py::test_the_pipeline_config_carries_no_rate_table"
            ),
            "Unchanged.",
        ),
        (
            "No registry in the lifecycle.",
            "BOUNDARY",
            "ADR-0035",
            "Unchanged.",
        ),
        (
            "No class-name resolution.",
            "BOUNDARY",
            "alphalab/runtime/snapshot.py:_require_object",
            "A recorded name is evidence, never an import.",
        ),
        (
            "No FX in alphalab.allocation.",
            "BOUNDARY",
            "ADR-0035",
            "Unchanged.",
        ),
        (
            "No migration of a v2 portfolio payload.",
            "BOUNDARY",
            "docs/STATE_MODEL.md",
            "The portfolio decoder refuses its versions 1 and 2.",
        ),
        (
            "AlphaLab still ships no FX data.",
            "EXTERNAL",
            "ROADMAP External dependencies",
            "Permanent.",
        ),
    ),
    "HIS-026": (
        (
            "alphalab.runtime.execution_pipeline._trade_record",
            "DELIVERED",
            "tests/regression/test_holding_period_and_sector.py",
            "Holding period and sector attributed since v2.x.",
        ),
        (
            "Mark-to-market position repricing is not implemented.",
            "DELIVERED",
            "tests/integration/test_mark_to_market_pipeline.py",
            "Since v2.1.",
        ),
        (
            "alphalab.replay is a standalone engine",
            "DELIVERED",
            "ADR-0010",
            "ReplayBacktest drives the pipeline since v2.2.",
        ),
        (
            "alphalab.data.feed.Bar and alphalab.market.bar.Bar",
            "DELIVERED",
            "ADR-0011; tests/regression/test_shared_names_stay_distinct.py",
            "Wire and canonical bars, distinct on purpose; the third Bar removed.",
        ),
        (
            "The broker / brokers, marketdata / data / feed",
            "DELIVERED",
            "ADR-0011; ADR-0012; CHANGELOG 2.17.0",
            "Each decided: kept distinct, merged or removed.",
        ),
    ),
    "HIS-027": (
        (
            "The OMS order book is the execution path's remaining super-linear term.",
            "DELIVERED",
            "PRF-003; PRF-008; tests/regression/test_marketdata_and_broker_complexity.py",
            "Persistent maps since v2.x; measured linear.",
        ),
        (
            "OMSState cannot be JSON-serialized as a whole state",
            "DELIVERED",
            "alphalab/oms/snapshot.py",
            "OMS snapshot since v2.2.",
        ),
        (
            "A risk-rejected request does not release its allocation reservation",
            "DELIVERED",
            (
                "tests/integration/test_backtest_pipeline.py::test_a_request_risk_refuses_never_reaches_the_oms"
            ),
            "Mutation M07 pins it.",
        ),
        (
            "dataclasses.asdict cannot be extended",
            "LIMITATION",
            "alphalab/common/serialization.py",
            (
                "Unchanged: dataclass_to_dict and persistence.serialize are the serialization "
                "boundary."
            ),
        ),
        (
            "Valuation is single-currency.",
            "DELIVERED",
            "ADR-0035; API-004",
            "Multi-currency books and valuation_in.",
        ),
        (
            "_trade_record still hard-codes",
            "DELIVERED",
            "tests/regression/test_holding_period_and_sector.py",
            "As HIS-026.",
        ),
    ),
    "HIS-028": (
        (
            "Unchanged and explicitly excluded",
            "DELIVERED",
            (
                "ADR-0031; ADR-0033; ADR-0035; ADR-0016; ADR-0017; ADR-0030; BND-002; CHANGELOG "
                "2.17.0"
            ),
            (
                "Each delivered or decided later, as HIS-004; the two ExecutionReceived "
                "duplicates were renamed apart (API-001)."
            ),
        ),
    ),
    "HIS-029": (
        (
            "FX and true multi-currency valuation",
            "DELIVERED",
            "ADR-0033; ADR-0035",
            "v2.16-v2.17.",
        ),
        (
            "instrument currency reaching Position / CashLedger",
            "DELIVERED",
            "ADR-0028",
            "v2.12.",
        ),
        (
            "Bar.currency",
            "DELIVERED",
            "alphalab/market/bar.py",
            "The canonical bar carries its currency.",
        ),
        (
            "OMSSnapshot.schema_version and the OMS history/events envelope",
            "DELIVERED",
            "alphalab/oms/snapshot.py",
            "Versioned since v2.9.",
        ),
        (
            "AllocationState persistence and session round-trip",
            "DELIVERED",
            "alphalab/allocation/snapshot.py",
            "v2.9.",
        ),
        (
            "governance actors and enterprise RBAC",
            "DELIVERED",
            "ADR-0018 (v2.16); BND-002",
            "Actors recorded; RBAC is the host's.",
        ),
        (
            "richer persisted evidence provenance",
            "DELIVERED",
            "ADR-0017; OFE-016",
            "Evidence derives the dataset; the evidence store since v3.12.",
        ),
        (
            "ResearchState dataset identity",
            "SUPERSEDED",
            "ADR-0037",
            "Studies name their dataset.",
        ),
        (
            "StrategyContext population",
            "DELIVERED",
            "ADR-0026",
            "v2.10.",
        ),
        (
            "live transport, streaming and reconnect",
            "DELIVERED",
            "ADR-0031",
            "v2.15.",
        ),
        (
            "sector classification",
            "DELIVERED",
            "ADR-0027",
            "v2.11; the data is EXTERNAL.",
        ),
        (
            "a dataset registry",
            "BOUNDARY",
            "ADR-0036",
            "As HIS-006.",
        ),
        (
            "an artifact store",
            "DELIVERED",
            "ADR-0031",
            "v2.15.",
        ),
        (
            "and the removal of integrations, kernel",
            "REMOVED",
            "CHANGELOG 2.17.0 section 5",
            "v2.17.",
        ),
    ),
    "HIS-030": (
        (
            "StrategyStateProtocol and StrategyContext completion",
            "DELIVERED",
            "ADR-0025; ADR-0026",
            "v2.10.",
        ),
        (
            "unifying SessionState and BacktestState",
            "DELIVERED",
            "ADR-0030",
            "v2.14.",
        ),
        (
            "promoting the four cross-package private decoders",
            "BOUNDARY",
            "alphalab/runtime/run_snapshot.py",
            (
                "Still private and imported across one package boundary, by the owner of the "
                "state they decode; not public API."
            ),
        ),
        (
            "schema constants for market, risk, execution",
            "SUPERSEDED",
            "ADR-0023",
            "As HIS-013.",
        ),
        (
            "a migration framework or version-translation layer",
            "DELIVERED",
            "PER-001",
            "v3.10.",
        ),
        (
            "broker transport, streaming market data and reconnect",
            "DELIVERED",
            "ADR-0031",
            "v2.15.",
        ),
        (
            "artifact storage",
            "DELIVERED",
            "ADR-0031",
            "v2.15.",
        ),
        (
            "a security master and sector attribution",
            "DELIVERED",
            "ADR-0016; ADR-0027",
            "v2.7-v2.11.",
        ),
        (
            "an FX rate source and true multi-currency valuation",
            "DELIVERED",
            "ADR-0033; ADR-0035",
            "v2.16-v2.17.",
        ),
        (
            "the approval workflow over alphalab.enterprise's RBAC",
            "DELIVERED",
            "ADR-0033; BND-002",
            "Approval on the lifecycle since v2.16; RBAC is the host's since v3.11.",
        ),
        (
            "unifying OMSState and BrokerState authority",
            "BOUNDARY",
            "tests/regression/test_shared_names_stay_distinct.py",
            "As HIS-014.",
        ),
        (
            "and the removal of integrations, kernel",
            "REMOVED",
            "CHANGELOG 2.17.0 section 5",
            "v2.17.",
        ),
    ),
    "HIS-031": (
        (
            "StrategyContext.history and .universe",
            "DELIVERED",
            "alphalab/strategy/context.py",
            "As HIS-016.",
        ),
        (
            "allocation visibility through the context",
            "BOUNDARY",
            "BDY-002",
            "Unchanged.",
        ),
        (
            "mutable runtime services in any context field",
            "BOUNDARY",
            "ADR-0026",
            "Permanent.",
        ),
        (
            "reviving on_fill, on_order or on_timer",
            "DELIVERED",
            "OFE-014",
            "v3.11.",
        ),
        (
            "unifying SessionState and BacktestState",
            "DELIVERED",
            "ADR-0030",
            "v2.14.",
        ),
        (
            "promoting the four cross-package private decoders",
            "BOUNDARY",
            "alphalab/runtime/run_snapshot.py",
            "As HIS-030.",
        ),
        (
            "broker transport, streaming market data and reconnect",
            "DELIVERED",
            "ADR-0031",
            "v2.15.",
        ),
        (
            "artifact storage",
            "DELIVERED",
            "ADR-0031",
            "v2.15.",
        ),
        (
            "a security master and sector attribution",
            "DELIVERED",
            "ADR-0016; ADR-0027",
            "v2.7-v2.11.",
        ),
        (
            "an FX rate source and true multi-currency valuation",
            "DELIVERED",
            "ADR-0033; ADR-0035",
            "v2.16-v2.17.",
        ),
        (
            "the approval workflow over alphalab.enterprise's RBAC",
            "DELIVERED",
            "ADR-0033; BND-002",
            "As HIS-030.",
        ),
        (
            "and the removal of integrations, kernel",
            "REMOVED",
            "CHANGELOG 2.17.0 section 5",
            "v2.17.",
        ),
    ),
    "HIS-032": (
        (
            "Any taxonomy or classification dataset",
            "EXTERNAL",
            "BDY-013",
            "No reference data.",
        ),
        (
            "classification dimensions other than sector",
            "DELIVERED",
            "OFE-001",
            "v3.12.",
        ),
        (
            "a canonical or case-folded sector vocabulary",
            "BOUNDARY",
            "ADR-0027",
            "As HIS-017.",
        ),
        (
            "distinguishing *why* a sector is unknown",
            "BOUNDARY",
            "ADR-0027",
            "As HIS-017.",
        ),
        (
            "sector-based risk limits",
            "DELIVERED",
            "OFE-001",
            "v3.12.",
        ),
        (
            "persisting the InstrumentRegistry, or checking on restore",
            "DELIVERED",
            "alphalab/instrument/snapshot.py",
            "As HIS-017.",
        ),
        (
            "InstrumentRecord.currency reaching Position.currency",
            "DELIVERED",
            "ADR-0028",
            "v2.12.",
        ),
        (
            "StrategyContext.history and .universe",
            "DELIVERED",
            "alphalab/strategy/context.py",
            "As HIS-016.",
        ),
        (
            "broker transport, streaming market data and reconnect",
            "DELIVERED",
            "ADR-0031",
            "v2.15.",
        ),
        (
            "artifact storage",
            "DELIVERED",
            "ADR-0031",
            "v2.15.",
        ),
        (
            "the approval workflow over alphalab.enterprise's RBAC",
            "DELIVERED",
            "ADR-0033; BND-002",
            "As HIS-030.",
        ),
        (
            "and the removal of integrations, kernel",
            "REMOVED",
            "CHANGELOG 2.17.0 section 5",
            "v2.17.",
        ),
    ),
    "HIS-033": (
        (
            "Ten standalone packages still accumulate quadratically",
            "DELIVERED",
            "CHANGELOG 2.17.0 section 4; tests/regression/test_standalone_state_scaling.py",
            "Converted in v2.17; the scheduler measured linear.",
        ),
        (
            "ResearchPayload.parameters is a dict on a frozen dataclass",
            "DELIVERED",
            "alphalab/research/protocol.py:ResearchPayload",
            "A read-only Mapping since v2.17.",
        ),
        (
            "brokers.protocol.BrokerProtocol shares a name",
            "DELIVERED",
            "CHANGELOG 2.17.0",
            "Renamed BrokerConnectorProtocol.",
        ),
        (
            "Dispatcher.dispatch_event still takes event: Any",
            "DELIVERED",
            "tests/regression/test_dispatcher_event_typing.py",
            (
                "Typed. (The item's closing sentence, that none of the four is on the execution "
                "path, held.)"
            ),
        ),
    ),
    "HIS-034": (
        (
            "v3.11: the boundary",
            "DELIVERED",
            ("docs/audit/PRE_V4_COMPLETION_LEDGER.yaml (v311_outcome, v312_outcome, v313_outcome)"),
            "Every item delivered by v3.11-v3.13 under its ledger ID.",
        ),
    ),
    "HIS-035": (
        (
            "v3.12.0: exchange calendars inside simulation",
            "DELIVERED",
            "EXE-010; docs/audit/PRE_V4_COMPLETION_LEDGER.yaml",
            "Delivered in v3.12-v3.13 under their ledger IDs.",
        ),
    ),
    "HIS-036": (
        (
            "v3.13.0: the final pre-v4 audit",
            "DELIVERED",
            "TST-015; ADR-0048",
            "The v3.13 audit and its 23 findings.",
        ),
    ),
    "HIS-037": (
        (
            "Per-order memory [PRF-011]",
            "LIMITATION",
            "PRF-011",
            "Re-measured in v4.0 (docs/audit/V4_RELEASE_AUDIT.md); kept.",
        ),
        (
            "Other hosts: certified identities",
            "LIMITATION",
            "LIM-005",
            (
                "Stated only in the CHANGELOG until v4.0; now a ledger entry. The certificate "
                "records the host and --check names a mismatch."
            ),
        ),
        (
            "The one-asset paths against 3.11 [PRF-012",
            "LIMITATION",
            "PRF-012",
            "Kept.",
        ),
        (
            "The limitations the release ADRs state",
            "LIMITATION",
            "LIM-001; LIM-002; LIM-003",
            "Kept.",
        ),
    ),
    "HIS-038": (
        (
            "UNKNOWN: how the transports behave against a real venue.",
            "EXTERNAL",
            "ROADMAP External dependencies",
            "Verification against a commercial venue needs its credentials and egress.",
        ),
        (
            "UNKNOWN: whether the linear scaling holds",
            "LIMITATION",
            "LIM-006; docs/audit/V4_RELEASE_AUDIT.md",
            "The measured operating envelope is stated; beyond it is extrapolation.",
        ),
        (
            "UNKNOWN: whether the single-threaded model is sufficient",
            "LIMITATION",
            "LIM-006",
            (
                "Single-threaded by design; sharding is the host's (one run per process) and "
                "nothing has needed more."
            ),
        ),
        (
            "FIXED in v3.10 (KD-001\u2013003)",
            "DELIVERED",
            "KD-001; KD-002; KD-003",
            "v3.10.",
        ),
        (
            "FIXED in v3.10 (TST-001)",
            "DELIVERED",
            "TST-001; tests/regression/_timing.py",
            "v3.10.",
        ),
        (
            "MEASURED since v3.12: how far the pure-Python construction solver",
            "LIMITATION",
            "PRF-005; PRF-013",
            "Measured and stated.",
        ),
        (
            "UNKNOWN: how real venues order amendments",
            "EXTERNAL",
            "BRK-002; ADR-0044",
            "Sequence numbers since v3.11; delivery order is the adapter's.",
        ),
        (
            "FIXED in v3.10 (KD-004): ingest_rows identified what its caller's source said",
            "SUPERSEDED",
            "KD-004 (v3.10)",
            (
                "Rows are identified by their content since v3.10. Until v4.0 this item "
                "read 'KNOWN CAVEAT: ingest_rows identifies what its caller's source says' "
                "as if still true; v4.0 corrected the text."
            ),
        ),
    ),
    "HIS-039": (
        (
            "Should the Signal Router's allocation/netting layer",
            "DELIVERED",
            "alphalab/allocation",
            "A distinct allocation authority (ADR-0015).",
        ),
        (
            "GPU-accelerated strategies",
            "BOUNDARY",
            "OFE-026",
            "Hook latency and threading are the host's.",
        ),
        (
            "Cross-asset (equities + futures + FX + crypto + options) instrument identity",
            "DELIVERED",
            "ADR-0016; ACC-005",
            "One identity authority; instrument economics on the canonical path.",
        ),
    ),
}


def _normalize(text: str) -> str:
    return " ".join(re.sub(r"\*\*|`", "", text).split())


def _changelog_section(version: str, heading: str) -> str:
    text = (ROOT / "CHANGELOG.md").read_text(encoding="utf-8")
    release = text.split(f"\n# [{version}]", 1)[1].split("\n# [", 1)[0]
    body = release.split(f"\n## {heading}\n", 1)[1]
    return re.split(r"\n#{1,2} |\n---", body, maxsplit=1)[0]


def _markdown_section(path: str, heading: str) -> str:
    text = (ROOT / path).read_text(encoding="utf-8")
    match = re.search(rf"^(#+) {re.escape(heading)}\s*$", text, re.M)
    if match is None:
        raise LookupError(f"{path} has no section {heading!r}")
    level = len(match.group(1))
    rest = text[match.end() :]
    end = re.search(rf"^#{{1,{level}}} |^---$", rest, re.M)
    return rest[: end.start()] if end else rest


def _section_text(section: Section) -> str:
    if section.path.startswith("CHANGELOG.md#"):
        return _changelog_section(section.path.split("#", 1)[1], section.heading)
    return _markdown_section(section.path, section.heading)


def stated_items() -> dict[str, list[str]]:
    """Every item each section states, normalized, keyed by its ledger entry."""

    found: dict[str, list[str]] = {}
    for section in SECTIONS:
        body = _section_text(section).strip()
        if section.shape == "bullets":
            items = re.findall(r"^[-*] (.+?)(?=\n[-*] |\n\n|\Z)", body, re.M | re.S)
        elif section.shape == "semicolons":
            paragraph = body.split("\n\n", 1)[0]
            items = [part for part in re.split(r";\s+", paragraph) if part.strip()]
        else:
            items = [body]
        found[section.ledger_id] = [_normalize(item) for item in items]
    return found


def matches() -> dict[str, list[tuple[str, Row | None, int]]]:
    """Each stated item, the one row that classifies it (or ``None``), and how many rows matched."""

    out: dict[str, list[tuple[str, Row | None, int]]] = {}
    for ledger_id, items in stated_items().items():
        rows = CLASSIFICATION.get(ledger_id, ())
        listed: list[tuple[str, Row | None, int]] = []
        for item in items:
            hits = [row for row in rows if item.startswith(row[0])]
            listed.append((item, hits[0] if len(hits) == 1 else None, len(hits)))
        out[ledger_id] = listed
    return out


def problems() -> list[str]:
    """Every item no single row classifies, every row no item uses, every unknown status."""

    found: list[str] = []
    for ledger_id, listed in matches().items():
        used: set[str] = set()
        for item, row, count in listed:
            if row is None:
                found.append(f"{ledger_id}: {count} rows match {item[:80]!r}")
            else:
                used.add(row[0])
        for row in CLASSIFICATION.get(ledger_id, ()):
            if row[0] not in used:
                found.append(f"{ledger_id}: row {row[0]!r} classifies nothing stated")
            if row[1] not in STATUSES:
                found.append(f"{ledger_id}: unknown status {row[1]!r}")
    for ledger_id in set(CLASSIFICATION) - {section.ledger_id for section in SECTIONS}:
        found.append(f"{ledger_id}: classification for no section")
    return found


def _yaml(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


_EVIDENCE = (
    "v4.0 reading of the section in full, each item checked against the code, the tests "
    "and later releases; the classification is docs/audit/scripts/historical_inventory_v4.py."
)
_REQUIRED = (
    "Classify every item with evidence; fix what conceals a defect; put accepted future "
    "work on the ROADMAP with acceptance criteria."
)
_RATIONALE = "A deferral that no ledger entry holds is one nobody re-reads before a freeze."
_TEST = (
    "tests/regression/test_every_adr_deferral_is_classified.py"
    "::test_every_historical_item_is_classified_once"
)


def ledger_block() -> str:
    """The ``HIS-xxx`` ledger entries, one per section."""

    lines = [MARKER]
    listed = matches()
    for section in SECTIONS:
        items = listed[section.ledger_id]
        statuses = sorted({row[1] for _, row, _ in items if row is not None})
        futures = [row[2] for _, row, _ in items if row is not None and row[1] == "FUTURE"]
        finding = (
            f"{section.origin} stated {len(items)} deferred, excluded or open items under "
            f"{section.heading!r}, and no ledger entry classified them until the v4.0 "
            "archaeology (TST-017)."
        )
        outcome = "Future work: " + "; ".join(futures) if futures else "No item is left open."
        lines += [
            f'  - id: "{section.ledger_id}"',
            '    category: "historical_inventory"',
            '    subsystem: "history"',
            f"    module: {_yaml(section.path + ' (' + section.heading + ')')}",
            f"    finding: {_yaml(finding)}",
            f"    evidence: {_yaml(_EVIDENCE)}",
            '    severity: "informational"',
            f"    current_state: {_yaml('Classified item by item: ' + ', '.join(statuses) + '.')}",
            f"    required_change: {_yaml(_REQUIRED)}",
            f"    rationale: {_yaml(_RATIONALE)}",
            '    release: "v4.0.0"',
            '    implementation_status: "implemented (v4.0.0): every item classified"',
            f"    test_status: {_yaml(_TEST)}",
            '    benchmark_status: "n/a"',
            '    documentation_status: "docs/audit/V4_HISTORICAL_INVENTORY.md"',
            '    api_impact: "none"',
            '    architecture_impact: "none"',
            '    performance_impact: "neutral"',
            "    v4_required: true",
            '    v4_disposition: "CLASSIFY"',
            '    verified: "v4.0 archaeology"',
            f"    v4_outcome: {_yaml(outcome)}",
            "    items:",
        ]
        for item, row, _ in items:
            assert row is not None, item
            lines.append(f"      - {_yaml(f'{row[0]} :: {row[1]} :: {row[2]} :: {row[3]}')}")
    return "\n".join(lines) + "\n"


def document() -> str:
    """``docs/audit/V4_HISTORICAL_INVENTORY.md``."""

    listed = matches()
    total = sum(len(items) for items in listed.values())
    counts: dict[str, int] = {}
    for items in listed.values():
        for _, row, _ in items:
            if row is not None:
                counts[row[1]] = counts.get(row[1], 0) + 1
    out = [
        "# AlphaLab v4.0 Historical Inventory",
        "",
        "Generated by `docs/audit/scripts/historical_inventory_v4.py` from the classification",
        "it holds; `tests/regression/test_every_adr_deferral_is_classified.py` fails when an ADR",
        "or the CHANGELOG states an item this inventory does not classify, or when this file",
        "is stale. Do not edit it by hand.",
        "",
        "The pre-v4 ledger (`PRE_V4_COMPLETION_LEDGER.yaml`) already classified ROADMAP's",
        "boundaries and optional list (v3.10) and the release ADRs' known limitations and",
        "deferred items (ADR-0042 to ADR-0044, v3.13). This inventory covers what neither",
        "read: the v2-era ADRs' non-goal sections, the CHANGELOG's gap, limitation, deferral",
        "and still-open sections from v2.0.0 to v3.13.0, and the open questions of",
        "`nowandfuture.md` and the strategy-runtime design. Each section is one `HIS-xxx`",
        "ledger entry; each item its own row below.",
        "",
        f"**{total} items in {len(SECTIONS)} sections:** "
        + ", ".join(f"{status} {counts.get(status, 0)}" for status in STATUSES)
        + f" -- {sum(counts.values())} in all. Every one is history the pre-v4 inventory",
        "had not read; what v4.0 itself wrote about them is prose beside the lists, not",
        "an item in them.",
        "",
        "| Status | Meaning |",
        "| --- | --- |",
        *[f"| {status} | {meaning} |" for status, meaning in STATUSES.items()],
        "",
    ]
    for section in SECTIONS:
        out += [
            f"## {section.ledger_id} — {section.origin}: {section.heading}",
            "",
            f"Source: `{section.path}`.",
            "",
            "| Item | Status | Evidence | Disposition |",
            "| --- | --- | --- | --- |",
        ]
        for item, row, _ in listed[section.ledger_id]:
            assert row is not None, item
            shown = item if len(item) <= 110 else item[:107] + "..."
            out.append(
                f"| {shown.replace('|', '/')} | {row[1]} | {row[2].replace('|', '/')} | "
                f"{row[3].replace('|', '/')} |"
            )
        out.append("")
    return "\n".join(out)


def _ledger_with_block() -> str:
    text = LEDGER.read_text(encoding="utf-8")
    head = text.split("\n" + MARKER, 1)[0].rstrip("\n") + "\n"
    return head + ledger_block()


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    found = problems()
    if found:
        print("\n".join(found), file=sys.stderr)
        return 1
    if args.write:
        LEDGER.write_text(_ledger_with_block(), encoding="utf-8")
        DOCUMENT.write_text(document(), encoding="utf-8")
        return 0
    stale = [
        path.name
        for path, expected in ((LEDGER, _ledger_with_block()), (DOCUMENT, document()))
        if not path.is_file() or path.read_text(encoding="utf-8") != expected
    ]
    if stale:
        print(f"stale: {stale}; run with --write", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
