"""Immutable interface protocol for Market Data Providers."""

from typing import Any, Protocol

from alphalab.marketdata.feed import Bar, OrderBook, Quote, Trade
from alphalab.marketdata.timeframe import Timeframe


class MarketDataProtocol(Protocol):
    def connect(self) -> bool: ...
    def disconnect(self) -> bool: ...
    def subscribe(self, symbol: str, timeframe: Timeframe) -> bool: ...
    def unsubscribe(self, symbol: str, timeframe: Timeframe) -> bool: ...
    
    def request_history(
        self, symbol: str, timeframe: Timeframe, start: float, end: float
    ) -> tuple[Bar, ...]: ...
    
    def latest_quote(self, symbol: str) -> Quote | None: ...
    def latest_trade(self, symbol: str) -> Trade | None: ...
    def latest_bar(self, symbol: str) -> Bar | None: ...
    def order_book(self, symbol: str) -> OrderBook | None: ...
    def health(self) -> dict[str, Any]: ...