"""Reading a lock file into a dependency manifest (ledger OFE-019, v3.13).

The texts below are what pip-compile, ``uv pip compile``, uv and Poetry write,
cut to a few packages. A manifest read from one says what the lock says: the
pins, how complete they are, and an artifact digest only where the lock names
one artifact.
"""

from __future__ import annotations

import pytest

from alphalab.lifecycle import (
    DependencyCompleteness,
    DependencyManifest,
    DependencyPin,
    LifecycleInputError,
    LockFormat,
    read_lock_file,
)

A = "a" * 64
B = "b" * 64
C = "c" * 64
D = "d" * 64

PIP_COMPILE = f"""#
# This file is autogenerated by pip-compile with Python 3.12
# by the following command:
#
#    pip-compile --generate-hashes requirements.in
#
--index-url https://pypi.org/simple

certifi==2024.8.30 \\
    --hash=sha256:{A} \\
    --hash=sha256:{B}
    # via requests
idna==3.10 \\
    --hash=sha256:{C}
    # via requests
requests[socks]==2.32.3 ; python_version >= "3.8" \\
    --hash=sha256:{D}
    # via -r requirements.in
"""

UV_PIP_COMPILE = """# This file was autogenerated by uv via the following command:
#    uv pip compile requirements.in -o requirements.txt
numpy==2.1.2
    # via -r requirements.in
"""

UV_LOCK = f"""version = 1
requires-python = ">=3.12"

[[package]]
name = "certifi"
version = "2024.8.30"
source = {{ registry = "https://pypi.org/simple" }}
sdist = {{ url = "https://files/certifi.tar.gz", hash = "sha256:{A}", size = 168507 }}
wheels = [
    {{ url = "https://files/certifi.whl", hash = "sha256:{B}", size = 167321 }},
]

[[package]]
name = "my-strategy"
version = "0.1.0"
source = {{ editable = "." }}
dependencies = [{{ name = "requests" }}]

[[package]]
name = "requests"
version = "2.32.3"
source = {{ registry = "https://pypi.org/simple" }}
wheels = [
    {{ url = "https://files/requests.whl", hash = "sha256:{C}", size = 64928 }},
]
"""

POETRY_HEADER = "# This file is automatically @generated by Poetry 1.8.3"
POETRY_LOCK = (
    POETRY_HEADER
    + f""" and should not be changed by hand.

[[package]]
name = "requests"
version = "2.32.3"
description = "Python HTTP for Humans."
optional = false
python-versions = ">=3.8"
files = [
    {{file = "requests-2.32.3-py3-none-any.whl", hash = "sha256:{A}"}},
    {{file = "requests-2.32.3.tar.gz", hash = "sha256:{B}"}},
]

[[package]]
name = "internal-lib"
version = "1.4.0"
description = ""
optional = false
python-versions = "*"
files = [
    {{file = "internal_lib-1.4.0.tar.gz", hash = "sha256:{C}"}},
]

[package.source]
type = "legacy"
url = "https://index.example/simple"
reference = "internal"

[[package]]
name = "vendored"
version = "0.2.0"
description = ""
optional = false
python-versions = "*"
files = []

[package.source]
type = "git"
url = "https://example.com/vendored.git"
reference = "HEAD"
resolved_reference = "0123abc"

[metadata]
lock-version = "2.0"
python-versions = "^3.12"
content-hash = "{D}"
"""
)


def _versions(manifest: DependencyManifest) -> dict[str, tuple[str, str | None]]:
    return {pin.normalized_name: (pin.version, pin.artifact_sha256) for pin in manifest.pins}


def test_a_pip_compile_lock_is_an_exact_closure_with_its_single_hashes() -> None:
    manifest = read_lock_file(PIP_COMPILE, LockFormat.PIP_COMPILE)
    assert manifest.completeness is DependencyCompleteness.EXACT_CLOSURE
    assert _versions(manifest) == {
        # Two artifacts listed: which one was installed is not said.
        "certifi": ("2024.8.30", None),
        "idna": ("3.10", C),
        "requests": ("2.32.3", D),
    }


def test_uv_pip_compile_output_is_read_the_same_way() -> None:
    manifest = read_lock_file(UV_PIP_COMPILE, LockFormat.PIP_COMPILE)
    assert manifest.completeness is DependencyCompleteness.EXACT_CLOSURE
    assert manifest.pins == (DependencyPin("numpy", "2.1.2"),)


def test_a_file_without_the_compilers_header_is_not_read_as_a_closure() -> None:
    plain = "requests==2.32.3\nidna==3.10\n"
    with pytest.raises(LifecycleInputError, match="header"):
        read_lock_file(plain, LockFormat.PIP_COMPILE)
    manifest = read_lock_file(plain, LockFormat.REQUIREMENTS)
    assert manifest.completeness is DependencyCompleteness.DIRECT_ONLY
    assert len(manifest.pins) == 2


@pytest.mark.parametrize(
    "line",
    [
        "requests>=2.0",
        "requests",
        "mylib @ https://example.com/mylib-1.0.tar.gz",
        "-e ./local/package",
        "git+https://example.com/repo.git#egg=repo",
    ],
)
def test_a_requirement_that_is_not_one_exact_version_is_refused(line: str) -> None:
    with pytest.raises(LifecycleInputError, match="not an exact pin"):
        read_lock_file(line + "\n", LockFormat.REQUIREMENTS)


def test_a_uv_lock_leaves_out_its_own_project_and_pins_the_rest() -> None:
    manifest = read_lock_file(UV_LOCK, LockFormat.UV_LOCK)
    assert manifest.completeness is DependencyCompleteness.EXACT_CLOSURE
    assert _versions(manifest) == {
        "certifi": ("2024.8.30", None),  # a source distribution and a wheel
        "requests": ("2.32.3", C),
    }


def test_a_package_from_a_source_a_pin_cannot_state_is_refused_unless_excluded() -> None:
    with pytest.raises(LifecycleInputError, match="git source"):
        read_lock_file(POETRY_LOCK, LockFormat.POETRY_LOCK)
    manifest = read_lock_file(POETRY_LOCK, LockFormat.POETRY_LOCK, exclude=["Vendored"])
    assert _versions(manifest) == {
        "requests": ("2.32.3", None),
        "internal-lib": ("1.4.0", C),  # a private index is still an index
    }
    git_in_uv = UV_LOCK.replace(
        'source = { registry = "https://pypi.org/simple" }\nwheels = [\n    { url = "https://files/requests.whl"',
        'source = { git = "https://example.com/requests.git" }\nwheels = [\n    { url = "https://files/requests.whl"',
    )
    with pytest.raises(LifecycleInputError, match="not a registry"):
        read_lock_file(git_in_uv, LockFormat.UV_LOCK)


def test_one_distribution_at_two_versions_is_refused() -> None:
    twice = UV_LOCK + UV_LOCK.split("[[package]]", 3)[3].join(["[[package]]", ""]).replace(
        '"2.32.3"', '"2.31.0"'
    )
    with pytest.raises(LifecycleInputError, match="more than one version"):
        read_lock_file(twice, LockFormat.UV_LOCK)


def test_excluded_names_are_compared_in_normal_form() -> None:
    manifest = read_lock_file(PIP_COMPILE, LockFormat.PIP_COMPILE, exclude=["Requests", "IDNA"])
    assert [pin.normalized_name for pin in manifest.pins] == ["certifi"]


def test_what_is_not_a_lock_is_refused() -> None:
    with pytest.raises(LifecycleInputError, match="LockFormat"):
        read_lock_file(UV_LOCK, "uv")  # type: ignore[arg-type]
    with pytest.raises(LifecycleInputError, match="not one string"):
        read_lock_file(UV_LOCK, LockFormat.UV_LOCK, exclude="requests")
    with pytest.raises(LifecycleInputError, match="TOML"):
        read_lock_file("[[package]\nname = ", LockFormat.UV_LOCK)
    with pytest.raises(LifecycleInputError, match="no \\[\\[package\\]\\]"):
        read_lock_file("version = 1\n", LockFormat.UV_LOCK)
