"""Immutable aggregation reports generated by the Studio."""

from dataclasses import dataclass, field


@dataclass(frozen=True, slots=True)
class StudioReport:
    report_id: str
    project_id: str
    report_type: str  # e.g., "Performance Summary", "Risk Summary"
    timestamp: float
    content: str
    metrics: tuple[float, ...] = field(default_factory=tuple)
