"""
Update an existing order.

Identity fields must remain unchanged.
"""

from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field

from alphalab.oms.exceptions import UnknownOrderError
from alphalab.oms.ids import OrderId
from alphalab.oms.order import Order


@dataclass(frozen=True, slots=True)
class OrderBook:
    """
    Immutable mapping index representing the full collection of orders.
    Modifications return copies with structural sharing.
    """

    _orders: Mapping[OrderId, Order] = field(default_factory=dict)
    _by_asset: Mapping[str, frozenset[OrderId]] = field(default_factory=dict)
    _by_strategy: Mapping[str, frozenset[OrderId]] = field(default_factory=dict)

    def add(self, order: Order) -> "OrderBook":
        """Adds an order to the book and index mappings."""
        new_orders = dict(self._orders)
        new_orders[order.order_id] = order

        new_by_asset = dict(self._by_asset)
        asset_set = set(new_by_asset.get(order.asset_id, set()))
        asset_set.add(order.order_id)
        new_by_asset[order.asset_id] = frozenset(asset_set)

        new_by_strat = dict(self._by_strategy)
        strat_set = set(new_by_strat.get(order.strategy_id, set()))
        strat_set.add(order.order_id)
        new_by_strat[order.strategy_id] = frozenset(strat_set)

        return OrderBook(_orders=new_orders, _by_asset=new_by_asset, _by_strategy=new_by_strat)

    def remove(self, order_id: OrderId) -> "OrderBook":
        """Removes an order fully from the book."""
        if order_id not in self._orders:
            raise UnknownOrderError(f"Cannot remove unknown order: {order_id}")

        order = self._orders[order_id]

        new_orders = dict(self._orders)
        del new_orders[order_id]

        new_by_asset = dict(self._by_asset)
        asset_set = set(new_by_asset.get(order.asset_id, set()))
        asset_set.discard(order_id)
        if not asset_set:
            del new_by_asset[order.asset_id]
        else:
            new_by_asset[order.asset_id] = frozenset(asset_set)

        new_by_strat = dict(self._by_strategy)
        strat_set = set(new_by_strat.get(order.strategy_id, set()))
        strat_set.discard(order_id)
        if not strat_set:
            del new_by_strat[order.strategy_id]
        else:
            new_by_strat[order.strategy_id] = frozenset(strat_set)

        return OrderBook(_orders=new_orders, _by_asset=new_by_asset, _by_strategy=new_by_strat)

    def replace(self, order: Order) -> "OrderBook":
        """Updates an existing order.
        Identity fields remain unchanged, so indices are preserved."""
        if order.order_id not in self._orders:
            raise UnknownOrderError(f"Cannot replace unknown order: {order.order_id}")

        new_orders = dict(self._orders)
        new_orders[order.order_id] = order

        return OrderBook(
            _orders=new_orders, _by_asset=self._by_asset, _by_strategy=self._by_strategy
        )

    def find(self, order_id: OrderId) -> Order:
        """Looks up an order by strictly unique OrderId."""
        if order_id not in self._orders:
            raise UnknownOrderError(f"Order not found: {order_id}")
        return self._orders[order_id]

    def contains(self, order_id: OrderId) -> bool:
        """Determines if the order exists within the book."""
        return order_id in self._orders

    def orders(self) -> Sequence[Order]:
        """Returns all managed orders."""
        return tuple(self._orders.values())

    def open_orders(self) -> Sequence[Order]:
        """Returns only orders in an active state."""
        return tuple(o for o in self._orders.values() if o.is_open)

    def orders_for_asset(self, asset_id: str) -> Sequence[Order]:
        """Looks up all orders mapped to a specific asset identifier."""
        order_ids = self._by_asset.get(asset_id, frozenset())
        return tuple(self._orders[oid] for oid in order_ids)

    def orders_for_strategy(self, strategy_id: str) -> Sequence[Order]:
        """Looks up all orders generated by a specific strategy identifier."""
        order_ids = self._by_strategy.get(strategy_id, frozenset())
        return tuple(self._orders[oid] for oid in order_ids)
