"""Reading a lock file into a dependency manifest.

A :class:`~alphalab.lifecycle.fingerprint.DependencyManifest` says which
distributions a strategy depends on and how complete that statement is. Until
v3.13 the caller built one by hand, typically by copying a lock file's pins
into code (ledger OFE-019). This module reads the lock file's text instead, so
the manifest says what the lock says -- no more, and nothing less.

What is read
------------

=========================== ================================================
:attr:`LockFormat.PIP_COMPILE` A requirements file *compiled* by pip-tools'
                            ``pip-compile`` or by ``uv pip compile``, which
                            pin the whole resolved closure and say so in the
                            header they write. Read as an
                            ``EXACT_CLOSURE``; a file without that header is
                            refused, because a hand-written file of pins does
                            not say what it leaves out.
:attr:`LockFormat.REQUIREMENTS` A requirements file of exact pins, written by
                            anyone. Read as ``DIRECT_ONLY``: the pins are
                            exact, and nothing says they are the closure.
:attr:`LockFormat.UV_LOCK`  ``uv.lock``. The whole resolution, every
                            dependency group included. An ``EXACT_CLOSURE``.
:attr:`LockFormat.POETRY_LOCK` ``poetry.lock``. The same.
=========================== ================================================

The text is supplied: nothing here opens a file, reads an environment or runs
a resolver -- the boundary ``DependencyCompleteness`` already states.

What is refused rather than approximated
----------------------------------------

* A requirement that is not one exact version: a range, a URL, a VCS checkout
  or a local path is identified by where it came from, which a
  :class:`~alphalab.lifecycle.fingerprint.DependencyPin` cannot state.
* A package a TOML lock takes from a git repository, a directory, a file or a
  URL, for the same reason. The project the lock belongs to -- uv's
  ``editable`` or ``virtual`` root -- is not a dependency of itself and is
  left out.
* One distribution resolved to two versions (a lock spanning environments with
  different resolutions): a manifest is one environment's, and choosing between
  the versions would be a guess. Name the ones to leave out with ``exclude``.

A pin carries an artifact digest only when the lock lists exactly one artifact
for it. A lock listing a source distribution and several wheels does not say
which one was installed, and recording one of them would claim it did.
"""

from __future__ import annotations

import re
import tomllib
from collections.abc import Iterable, Mapping, Sequence
from enum import Enum, auto
from typing import Any

from alphalab.lifecycle.exceptions import LifecycleInputError
from alphalab.lifecycle.fingerprint import (
    DependencyCompleteness,
    DependencyManifest,
    DependencyPin,
    normalize_distribution_name,
)

__all__ = ["LockFormat", "read_lock_file"]


class LockFormat(Enum):
    """Which kind of lock text is being read. See the module docstring."""

    PIP_COMPILE = auto()
    REQUIREMENTS = auto()
    UV_LOCK = auto()
    POETRY_LOCK = auto()


#: The first lines pip-compile and ``uv pip compile`` write.
_COMPILED_HEADERS = (
    "# This file is autogenerated by pip-compile",
    "# This file was autogenerated by uv via the following command:",
)

#: ``name[extras]==version ; markers`` -- extras and markers allowed, nothing else.
_PINNED = re.compile(
    r"^(?P<name>[A-Za-z0-9][A-Za-z0-9._-]*)(?:\[[^\]]*\])?\s*==\s*(?P<version>[^\s;\\]+)"
    r"\s*(?:;[^\\]*)?$"
)
_HASH = re.compile(r"--hash[=\s]+sha256:(?P<digest>[0-9a-fA-F]{64})")
_SHA256 = re.compile(r"^sha256:(?P<digest>[0-9a-fA-F]{64})$")


def _compiled(text: str) -> bool:
    """Whether the leading comment block carries a compiler's header.

    pip-compile opens with a bare ``#`` line and then its sentence; uv opens
    with its sentence. Either is looked for anywhere in the opening comments.
    """

    for line in text.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        if not stripped.startswith("#"):
            return False
        if stripped.startswith(_COMPILED_HEADERS):
            return True
    return False


def _logical_lines(text: str) -> list[str]:
    """Requirement lines with ``\\`` continuations joined and comments dropped."""

    lines: list[str] = []
    pending = ""
    for raw in text.splitlines():
        line = raw.split(" #", 1)[0].rstrip() if not raw.lstrip().startswith("#") else ""
        if line.endswith("\\"):
            pending += line[:-1] + " "
            continue
        joined = (pending + line).strip()
        pending = ""
        if joined:
            lines.append(joined)
    if pending.strip():
        lines.append(pending.strip())
    return lines


def _read_requirements(text: str, exclude: frozenset[str]) -> list[DependencyPin]:
    pins: list[DependencyPin] = []
    for line in _logical_lines(text):
        if line.startswith("-") and not line.startswith(("-e", "--editable")):
            continue  # --index-url, --find-links, --trusted-host and the like
        hashes = [match.group("digest").lower() for match in _HASH.finditer(line)]
        requirement = _HASH.sub("", line).strip()
        match = _PINNED.match(requirement)
        if match is None:
            raise LifecycleInputError(
                f"{requirement!r} is not an exact pin (name==version). A range, a URL, a VCS "
                "checkout or an editable path is identified by where it came from, which a "
                "DependencyPin cannot state."
            )
        name = match.group("name")
        if normalize_distribution_name(name) in exclude:
            continue
        pins.append(
            DependencyPin(
                name=name,
                version=match.group("version"),
                artifact_sha256=hashes[0] if len(hashes) == 1 else None,
            )
        )
    return pins


def _artifact_digest(package: Mapping[str, Any], name: str) -> str | None:
    """The one artifact's digest, or ``None`` when the lock lists other than one."""

    digests: list[str] = []
    for key in ("sdist",):
        entry = package.get(key)
        if isinstance(entry, Mapping) and isinstance(entry.get("hash"), str):
            digests.append(entry["hash"])
    for key in ("wheels", "files"):
        entries = package.get(key)
        if isinstance(entries, Sequence) and not isinstance(entries, str):
            digests.extend(
                entry["hash"]
                for entry in entries
                if isinstance(entry, Mapping) and isinstance(entry.get("hash"), str)
            )
    if len(digests) != 1:
        return None
    match = _SHA256.match(digests[0])
    if match is None:
        raise LifecycleInputError(
            f"{name}'s artifact digest {digests[0]!r} is not a sha256 digest."
        )
    return match.group("digest").lower()


def _read_toml_lock(
    text: str, lock_format: LockFormat, exclude: frozenset[str]
) -> list[DependencyPin]:
    try:
        document = tomllib.loads(text)
    except tomllib.TOMLDecodeError as error:
        raise LifecycleInputError(f"The lock is not valid TOML: {error}.") from error
    packages = document.get("package")
    if not isinstance(packages, list):
        raise LifecycleInputError("The lock has no [[package]] table; it records no resolution.")
    pins: list[DependencyPin] = []
    for package in packages:
        if not isinstance(package, Mapping):
            raise LifecycleInputError(f"A [[package]] entry is {package!r}, not a table.")
        name, version = package.get("name"), package.get("version")
        if not isinstance(name, str) or not isinstance(version, str):
            raise LifecycleInputError(f"A [[package]] entry has no name and version: {package!r}.")
        if normalize_distribution_name(name) in exclude:
            continue
        source = package.get("source")
        if lock_format is LockFormat.UV_LOCK and isinstance(source, Mapping):
            if "editable" in source or "virtual" in source:
                continue  # the project the lock belongs to
            if not {"registry"} >= set(source):
                raise LifecycleInputError(
                    f"{name} {version} comes from {dict(source)!r}, not a registry: it is "
                    "identified by that source, which a DependencyPin cannot state. Exclude it "
                    "by name to read the rest."
                )
        if (
            lock_format is LockFormat.POETRY_LOCK
            and isinstance(source, Mapping)
            and source.get("type") not in (None, "legacy")
        ):
            raise LifecycleInputError(
                f"{name} {version} comes from a {source.get('type')} source, not a package "
                "index: it is identified by that source, which a DependencyPin cannot state. "
                "Exclude it by name to read the rest."
            )
        pins.append(
            DependencyPin(
                name=name, version=version, artifact_sha256=_artifact_digest(package, name)
            )
        )
    return pins


def read_lock_file(
    text: str,
    lock_format: LockFormat,
    *,
    exclude: Iterable[str] = (),
) -> DependencyManifest:
    """The dependency manifest a lock file's text states.

    Args:
        text: The lock file's contents.
        lock_format: Which kind of lock it is. Required: the kinds differ in
            what their pins claim, and guessing from the text would let a
            hand-written file pass for a compiled one.
        exclude: Distribution names to leave out -- the strategy's own package,
            or a source the manifest cannot state -- compared in normalized
            form.

    Raises:
        LifecycleInputError: If ``lock_format`` is not a :class:`LockFormat`, a
            ``PIP_COMPILE`` text lacks the compiler's header, a requirement is
            not an exact pin, a package comes from a source a pin cannot state,
            the TOML does not parse, or one distribution is pinned twice.
    """

    if not isinstance(lock_format, LockFormat):
        raise LifecycleInputError(f"lock_format must be a LockFormat, got {lock_format!r}.")
    if isinstance(exclude, str):
        raise LifecycleInputError("exclude takes names, not one string.")
    excluded = frozenset(normalize_distribution_name(name) for name in exclude)

    if lock_format is LockFormat.PIP_COMPILE:
        if not _compiled(text):
            raise LifecycleInputError(
                "The text does not open with the header pip-compile or uv pip compile writes, "
                "so nothing says it is the whole closure. Read it as REQUIREMENTS (DIRECT_ONLY) "
                "or compile it."
            )
        pins = _read_requirements(text, excluded)
        completeness = DependencyCompleteness.EXACT_CLOSURE
    elif lock_format is LockFormat.REQUIREMENTS:
        pins = _read_requirements(text, excluded)
        completeness = (
            DependencyCompleteness.DIRECT_ONLY if pins else DependencyCompleteness.EXACT_CLOSURE
        )
    else:
        pins = _read_toml_lock(text, lock_format, excluded)
        completeness = DependencyCompleteness.EXACT_CLOSURE

    names = [pin.normalized_name for pin in pins]
    repeated = sorted({name for name in names if names.count(name) > 1})
    if repeated:
        raise LifecycleInputError(
            f"The lock pins {repeated} at more than one version -- a resolution for several "
            "environments. A manifest is one environment's; exclude the ones that differ, or "
            "lock for one environment."
        )
    return DependencyManifest(completeness=completeness, pins=tuple(pins))
