"""
AlphaLab Examples
=================

Example 68 : Rerun a Result from Its Manifest, Dependencies Read from a Lock

Difficulty : Advanced

Estimated Time : 10 minutes

Prerequisites
-------------

✓ Example 47 (reproducible research artifacts)

Topics
------

• A lock file read into the dependency manifest a strategy's fingerprint
  records -- pip-compile's closure, a hand-written file's pins, and what is
  refused rather than approximated
• A run re-executed from its manifest: REPRODUCED
• Another cost: INPUTS_DIFFER -- since v4.0 the record keeps how the simulator
  was configured, not only its type
• The same declared inputs trading differently: DIVERGED, and where the two
  records part
• Another dataset, or another lock: INPUTS_DIFFER, and nothing run

What this shows
---------------

Example 47 compared manifests a caller had built; whether the second came from
a real rerun was the caller's business. ``rerun_from_manifest`` does the rerun.
It checks the dataset, the strategy, the engine and its build against the
manifest before anything runs; it calls the caller's ``run`` once; it builds
the rerun's own manifest and assesses it; and, given the original result, it
reports the first paths at which the two runs' records differ. The strategy's
dependencies are read from the lock file's text by ``read_lock_file``, so the
fingerprint states what the lock states -- no more, and nothing less.

Run

    python examples/68_rerun_from_a_manifest.py
"""

import re
import textwrap
from collections.abc import Callable
from dataclasses import replace
from decimal import Decimal

from _strategy_evidence import (
    CLASSES,
    CLOSES,
    DEFINITION,
    SOURCES,
    STRATEGY_ID,
    banner,
    ingest_prices,
    run_backtest,
)

from alphalab.backtesting.state import BacktestResult
from alphalab.execution.simulator import ExecutionSimulator
from alphalab.execution.slippage import FixedSlippage
from alphalab.lifecycle import (
    DependencyManifest,
    LifecycleInputError,
    LifecycleState,
    LockFormat,
    StrategyFingerprint,
    code_identity_for,
    fingerprint_for_version,
    get_strategy_version,
    manifest_for_run,
    read_lock_file,
    register_strategy,
    rerun_from_manifest,
    research_configuration,
    running_build,
    running_engine,
)
from alphalab.strategy import StrategyDefinition

#: The digests are placeholders: this lock is illustrative, not of a real
#: environment. Everything else is what ``pip-compile --generate-hashes`` writes.
LOCK = """#
# This file is autogenerated by pip-compile with Python 3.12
# by the following command:
#
#    pip-compile --generate-hashes requirements.in
#
numpy==2.1.2 \\
    --hash=sha256:{one}
    # via
    #   -r requirements.in
    #   pandas
pandas==2.2.3 \\
    --hash=sha256:{two} \\
    --hash=sha256:{three}
    # via -r requirements.in
python-dateutil==2.9.0.post0 \\
    --hash=sha256:{four}
    # via pandas
pytz==2024.2 \\
    --hash=sha256:{five}
    # via pandas
six==1.16.0 \\
    --hash=sha256:{six}
    # via python-dateutil
tzdata==2024.2 \\
    --hash=sha256:{seven}
    # via pandas
""".format(
    one="1" * 64,
    two="2" * 64,
    three="3" * 64,
    four="4" * 64,
    five="5" * 64,
    six="6" * 64,
    seven="7" * 64,
)

_DIGEST = re.compile(r"[0-9a-f]{64}")


def rule(title: str) -> None:
    print()
    print(title)
    print("-" * len(title))


def say(text: str, indent: str = "  ") -> None:
    """A line of the report, its digests cut to twelve characters as git cuts a commit's."""

    shortened = _DIGEST.sub(lambda match: match.group()[:12], text)
    print(
        textwrap.fill(shortened, width=76, initial_indent=indent, subsequent_indent=indent + "  ")
    )


def strategy_under(dependencies: DependencyManifest) -> StrategyFingerprint:
    """The example strategy's fingerprint, its dependencies those of one lock."""

    state, reference = register_strategy(LifecycleState(), "ex-momentum", DEFINITION, 1.0)
    version = get_strategy_version(state.strategies, reference.name, reference.version)
    code = code_identity_for(CLASSES.require(STRATEGY_ID), "alphalab-examples", "3.13.0", SOURCES)
    research = research_configuration({"validation": "single in-sample backtest"})
    return fingerprint_for_version(version, code, dependencies, research, running_engine())


def main() -> None:
    banner(68, "Rerun a Result from Its Manifest")

    # ----------------------------------------------------------------- #
    rule("A lock file, read")

    locked = read_lock_file(LOCK, LockFormat.PIP_COMPILE)
    print(f"  completeness: {locked.completeness.name}")
    for pin in locked.pins:
        artifact = (
            f"sha256 {pin.artifact_sha256[:12]}"
            if pin.artifact_sha256 is not None
            else "no single artifact named"
        )
        print(f"    {pin.name + '==' + pin.version:<30} {artifact}")
    print()
    print("  pip-compile writes the whole resolved closure and says so in its header,")
    print("  so the manifest is an EXACT_CLOSURE. A pin carries an artifact's digest")
    print("  only where the lock lists one artifact: pandas lists two, and the lock")
    print("  does not say which of them was installed.")

    # ----------------------------------------------------------------- #
    rule("What a lock is read as, and what is refused")

    hand_written = "numpy==2.1.2\npandas==2.2.3\n"
    try:
        read_lock_file(hand_written, LockFormat.PIP_COMPILE)
        print("  NOT REFUSED")
    except LifecycleInputError as error:
        say("two pins read as compiled: refused --")
        say(str(error), indent="    ")
    direct = read_lock_file(hand_written, LockFormat.REQUIREMENTS)
    print(f"  the same two pins read as written: {direct.completeness.name}")
    try:
        read_lock_file("numpy>=2\n", LockFormat.REQUIREMENTS)
        print("  NOT REFUSED")
    except LifecycleInputError as error:
        say("a range: refused --")
        say(str(error), indent="    ")

    # ----------------------------------------------------------------- #
    rule("The run, and its manifest")

    dataset = ingest_prices()
    fingerprint = strategy_under(locked)
    engine, build = running_engine(), running_build()
    original = run_backtest(dataset)
    manifest = manifest_for_run(original, dataset, fingerprint, engine, build=build)
    say(f"result   : {manifest.result_id}")
    say(f"strategy : {fingerprint.fingerprint} (its six pins included)")
    say(f"engine   : {engine} (and its build: source digest, tz database)")

    runs: list[str] = []

    def rerun(
        label: str,
        simulator: ExecutionSimulator | None = None,
        definition: StrategyDefinition = DEFINITION,
    ) -> Callable[[], BacktestResult]:
        def run() -> BacktestResult:
            runs.append(label)
            return run_backtest(dataset, simulator=simulator, definition=definition)

        return run

    # ----------------------------------------------------------------- #
    rule("Rerun with the same inputs")

    report = rerun_from_manifest(
        manifest,
        rerun("same"),
        dataset=dataset,
        fingerprint=fingerprint,
        engine=engine,
        build=build,
        original=original,
    )
    print(f"  {report.outcome.name}")
    say(report.detail[0], indent="    ")

    # ----------------------------------------------------------------- #
    rule("Rerun with another cost")

    slipped = ExecutionSimulator(slippage_model=FixedSlippage(Decimal("0.05")))
    report = rerun_from_manifest(
        manifest,
        rerun("slipped", slipped),
        dataset=dataset,
        fingerprint=fingerprint,
        engine=engine,
        build=build,
        original=original,
    )
    print(f"  {report.outcome.name}")
    for line in report.detail:
        say(line, indent="    ")
    print()
    print("  The configuration is the rerun's own, so the rerun ran; its record then")
    print("  names a simulator charging 0.05 a share for slippage where the original's")
    print("  charged nothing. Until v4.0 the record kept the simulator by type alone,")
    print("  and this reported DIVERGED from the fills; now the inputs are seen to")
    print("  differ, which is what happened (ledger PER-008).")

    # ----------------------------------------------------------------- #
    rule("Rerun of the same declared inputs, trading differently")

    trims_more = replace(DEFINITION, parameters={"entry": 1000.0, "exit": -600.0})
    report = rerun_from_manifest(
        manifest,
        rerun("trims more", definition=trims_more),
        dataset=dataset,
        fingerprint=fingerprint,
        engine=engine,
        build=build,
        original=original,
    )
    print(f"  {report.outcome.name}")
    say(report.detail[0], indent="    ")
    print(f"  where the records part (the first {len(report.differences)}, in canonical order):")
    for line in report.differences[:2]:
        say(line, indent="    ")
    print(f"    ... and {len(report.differences) - 2} more")
    print()
    print("  Everything the manifest identifies matched -- the dataset, the declared")
    print("  strategy, the engine, the configuration -- and the run sold 600 where the")
    print("  original sold 400: a strategy run with parameters its declaration does not")
    print("  state. Only the record can tell, and it says where the two runs part.")

    # ----------------------------------------------------------------- #
    rule("Rerun with other inputs")

    before = len(runs)
    one_close_moved = ingest_prices(
        "EX-PRICES",
        tuple(close + Decimal("0.01") if day == 5 else close for day, close in enumerate(CLOSES)),
    )
    report = rerun_from_manifest(
        manifest,
        rerun("other dataset"),
        dataset=one_close_moved,
        fingerprint=fingerprint,
        engine=engine,
        build=build,
        original=original,
    )
    print(f"  one close moved by 0.01: {report.outcome.name}")
    for line in report.detail:
        say(line, indent="    ")

    numpy_bumped = read_lock_file(
        LOCK.replace("numpy==2.1.2", "numpy==2.1.3"), LockFormat.PIP_COMPILE
    )
    report = rerun_from_manifest(
        manifest,
        rerun("other lock"),
        dataset=dataset,
        fingerprint=strategy_under(numpy_bumped),
        engine=engine,
        build=build,
        original=original,
    )
    print(f"  numpy 2.1.3 in the lock: {report.outcome.name}")
    for line in report.detail:
        say(line, indent="    ")
    print(f"  reruns called for these two: {len(runs) - before}")
    print()
    print("  A rerun of other inputs establishes nothing about reproduction, so it is")
    print("  reported without being run. The fingerprint covers the dependency")
    print("  manifest, so an environment locked differently is, to the record, another")
    print("  strategy.")

    # ----------------------------------------------------------------- #
    rule("What it will not rerun")

    try:
        rerun_from_manifest(
            replace(manifest, result_id="0" * 64),
            rerun("altered"),
            dataset=dataset,
            fingerprint=fingerprint,
            engine=engine,
            build=build,
        )
        print("  NOT REFUSED")
    except LifecycleInputError as error:
        say("a manifest altered after it was written: refused --")
        say(str(error), indent="    ")
    print(f"  runs in all: {len(runs)} ({', '.join(runs)})")


if __name__ == "__main__":
    main()
