"""Zerodha provider protocol interface."""

from typing import Any, Protocol


class ZerodhaProtocol(Protocol):
    def connect(self) -> bool: ...
    def disconnect(self) -> bool: ...
    def authenticate(self, credentials: dict[str, str]) -> bool: ...
    def submit_order(self, order_payload: dict[str, Any]) -> dict[str, Any]: ...
    def cancel_order(self, order_id: str) -> bool: ...
    def modify_order(self, order_id: str, updates: dict[str, Any]) -> dict[str, Any]: ...
    def positions(self) -> dict[str, Any]: ...
    def orders(self) -> dict[str, Any]: ...
    def account(self) -> dict[str, Any]: ...
    def health(self) -> dict[str, Any]: ...
    def sync_portfolio(self) -> dict[str, Any]: ...
